// <auto-generated />
using System;
using API.Database.Accesorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Database.Accesorio.Migraciones
{
    [DbContext(typeof(ModuloAccesoriosExplosivosContext))]
    partial class ModuloAccesoriosExplosivosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Database.Accesorio.Entidades.CategoriasAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteCapacidadMaximaSedena")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteConsumoMaximaSedena")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadDeMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ConsumosAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaCerrado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaAlmacen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaJefe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaReciboHanka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumosAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.DestinosAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DestinosAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.EntradasAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadFacturada")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadFinal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Chofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraFactura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadDeMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntradasAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.FacturasAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadFacturada")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Conductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiferenciaPesoContraFacturado")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remanente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tolerancia")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FacturasAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ProductosAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadActual")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("ConsumoPromedioDiario")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("ConsumoPromedioDiarioCalculado")
                        .HasColumnType("decimal(30,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("FactorCorreccionKg")
                        .HasColumnType("decimal(30,2)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdConjunto")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteAlto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteBajo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteConsumoAlto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteConsumoMaximo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMaximo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMinimo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadDeMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdConjunto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Accesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ProveedoresAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tolerancia")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.ToTable("ProveedoresAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.SalidasAccesorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadASacar")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadCorregida")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadFinal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(30,2)");

                    b.Property<bool>("EsDevolucion")
                        .HasColumnType("bit");

                    b.Property<decimal>("FactorCorrecion")
                        .HasColumnType("decimal(30,2)");

                    b.Property<int>("IdConsumo")
                        .HasColumnType("int");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSalida")
                        .HasColumnType("int");

                    b.Property<string>("NumeroStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadDeMedida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdConsumo");

                    b.ToTable("SalidasAccesorios");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ProductosAccesorios", b =>
                {
                    b.HasOne("API.Database.Accesorio.Entidades.CategoriasAccesorios", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Accesorio.Entidades.ProductosAccesorios", "Conjunto")
                        .WithMany("AccesoriosAsociados")
                        .HasForeignKey("IdConjunto");

                    b.HasOne("API.Database.Accesorio.Entidades.ProveedoresAccesorios", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conjunto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.SalidasAccesorios", b =>
                {
                    b.HasOne("API.Database.Accesorio.Entidades.ConsumosAccesorios", "Consumo")
                        .WithMany("Salidas")
                        .HasForeignKey("IdConsumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumo");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ConsumosAccesorios", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("API.Database.Accesorio.Entidades.ProductosAccesorios", b =>
                {
                    b.Navigation("AccesoriosAsociados");
                });
#pragma warning restore 612, 618
        }
    }
}
