// <auto-generated />
using System;
using API.Database.Almacenamiento;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Database.Almacenamiento.Migraciones
{
    [DbContext(typeof(ModuloAlmacenamientoExplosivosContext))]
    [Migration("20251218221328_CorregirPropiedadNombre")]
    partial class CorregirPropiedadNombre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Database.Almacenamiento.Entidades.CargasDepositosAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicial")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NivelFinal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("NivelInicial")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("NumeroEconomico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VolumenCargado")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("VolumenCargadoReal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("VolumenFinal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("VolumenInicial")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.ToTable("CargasDepositosAlmacenamientos");
                });

            modelBuilder.Entity("API.Database.Almacenamiento.Entidades.DepositosAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlturaMaxima")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("AlturaOperativa")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadMaxima")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CapacidadOperativa")
                        .HasColumnType("decimal(30,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteAlto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteBajo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMaximo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMinimo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepositosAlmacenamiento");
                });

            modelBuilder.Entity("API.Database.Almacenamiento.Entidades.EquiposAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadActual")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("Capacidad")
                        .HasColumnType("decimal(30,2)");

                    b.Property<bool>("EsExterno")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroEconomico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquiposAlmacenamiento");
                });

            modelBuilder.Entity("API.Database.Almacenamiento.Entidades.EstatusDepositosAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Deposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispositivoDeMedicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HayAlarma")
                        .HasColumnType("bit");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteAlto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteBajo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMaximo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("LimiteMinimo")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PorcentajeNivel")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Volumen")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.ToTable("EstatusDepositosAlmacenamiento");
                });

            modelBuilder.Entity("API.Database.Almacenamiento.Entidades.MovimientosSupersacosAlmacenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadFinal")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("CantidadMovimiento")
                        .HasColumnType("decimal(30,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovimientosSupersacosAlmacenamiento");
                });
#pragma warning restore 612, 618
        }
    }
}
