// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Database.Recepcion.Migraciones
{
    [DbContext(typeof(ModuloRecepcionExplosivosContext))]
    [Migration("20251029151128_FechaHoraCreacionEnEntidades")]
    partial class FechaHoraCreacionEnEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Database.Recepcion.Entidades.ConductoresRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConductoresRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.EquiposRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTransportista")
                        .HasColumnType("int");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTransportista");

                    b.ToTable("EquiposRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.OrigenesRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrigenesRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.ProveedoresRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tolerancia")
                        .HasColumnType("decimal(30,2)");

                    b.HasKey("Id");

                    b.ToTable("ProveedoresRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.Recepciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadFactura")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Chofer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("DiferenciaEntreFechas")
                        .HasColumnType("decimal(30,2)");

                    b.Property<DateTime>("FechaHoraFactura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroBoletaFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdenEmbarque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PesoNeto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PesoTara")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Placas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFCProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recepciones");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.TransaccionesRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("DiferenciaPesoContraFacturado")
                        .HasColumnType("decimal(30,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRecepcion")
                        .HasColumnType("int");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KilosFactura")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("KilosTransaccion")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PesoNeto")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PesoTara")
                        .HasColumnType("decimal(30,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remanente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tolerancia")
                        .HasColumnType("decimal(30,2)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRecepcion");

                    b.ToTable("TransaccionesRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.TransportistasRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("IdUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("TransportistasRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.EquiposRecepcion", b =>
                {
                    b.HasOne("API.Database.Recepcion.Entidades.TransportistasRecepcion", "Transportista")
                        .WithMany("Equipos")
                        .HasForeignKey("IdTransportista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.TransaccionesRecepcion", b =>
                {
                    b.HasOne("API.Database.Recepcion.Entidades.Recepciones", "Recepcion")
                        .WithMany("TransaccionesRecepcion")
                        .HasForeignKey("IdRecepcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.TransportistasRecepcion", b =>
                {
                    b.HasOne("API.Database.Recepcion.Entidades.ProveedoresRecepcion", "Proveedor")
                        .WithMany("Transportistas")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.ProveedoresRecepcion", b =>
                {
                    b.Navigation("Transportistas");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.Recepciones", b =>
                {
                    b.Navigation("TransaccionesRecepcion");
                });

            modelBuilder.Entity("API.Database.Recepcion.Entidades.TransportistasRecepcion", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
